<?php

namespace Sopinet\Bundle\UserNotificationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserLiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLiveRepository extends EntityRepository
{
}
