<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseGroup as BaseGroup;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Group extends BaseGroup
{
    /**
     * @var integer $id
     */
    protected $id;
    
    /**
     * @ORM\ManyToMany(targetEntity="User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    protected $users;
    
    /**
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    protected $admin;
    
    /**
     * @ORM\ManyToMany(targetEntity="Trazeo\BaseBundle\Entity\Children")
     */
    protected $childrens;
    
    /**
     * @ORM\ManyToOne(targetEntity="Trazeo\BaseBundle\Entity\Route")
     */
    protected $routes;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Set Users
     */
    public function setUser(Application\Sonata\UserBundle\Entity\User $users) {
    	$this->users = $users;
    }
    
    /**
     * Get Users
     *
     * @return string
     */
    public function getUsers() {
    	return $this->Users;
    }
    
    
    /**
     * Set Admin
     */
    public function setAdmin(Application\Sonata\UserBundle\Entity\User $admin) {
    	$this->admin = $admin;
    }
    
    /**
     * Get Admin
     *
     * @return string
     */
    public function getAdmin() {
    	return $this->Admin;
    }
    
    /**
     * Set Childrens
     */
    public function setChildrens(trazeo\Trazeo\BaseBundle\Entity\Children $childrens) {
    	$this->childrens = $childrens;
    }
    
    /**
     * Get Childrens
     *
     * @return string
     */
    public function getChildrens() {
    	return $this->Childrens;
    }
    
    /**
     * Set Routes
     */
    public function setRoutes(trazeo\Trazeo\BaseBundle\Entity\Route $routes) {
    	$this->routes = $routes;
    }
    
    /**
     * Get Routes
     *
     * @return string
     */
    public function getRoutes() {
    	return $this->Routes;
    }
}