<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
	
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nick", type="string", length=255)
     */
    
    private $nick;
    
    /**
     * @ORM\ManyToOne(targetEntity="JJs\Bundle\GeonamesBundle\Entity\City")
     */
    
    private $city;
    
    /**
     * @ORM\ManyToOne(targetEntity="JJs\Bundle\GeonamesBundle\Entity\Country")
     */
    
    protected $country;
    
    /**
     * @ORM\ManyToOne(targetEntity="trazeo\Trazeo\BaseBundle\Entity\Children", inversedBy="Children")
     */
    private $childrens;
    
    /**
     * @ORM\ManyToMany(targetEntity="Application\Sonata\UserBundle\Entity\Group")
     * @ORM\JoinColumn(name="group_id", referencedColumnName="id")
     */
    protected $groups;
    
    /**
     * @ORM\OneToMany(targetEntity="Group")
     */
    protected $adminGroups;
    
    /**
     * @ORM\OneToMany(targetEntity="trazeo\Trazeo\BaseBundle\Entity\Route")
     */
    protected $adminRoutes;
    
    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Set nick
     *
     * @param string $nick
     *
     * @return Children
     */
    public function setNick($nick)
    {
    	$this->nick = $nick;
    
    	return $this;
    }
    
    /**
     * Get nick
     *
     * @return string
     */
    public function getNick()
    {
    	return $this->nick;
    }
    
    /**
     * Set City
     */
    public function setGroup(JJs\Bundle\GeonamesBundle\Entity\City $city) {
    	$this->city = $city;
    }
    
    /**
     * Get City
     *
     * @return string
     */
    public function getCity() {
    	return $this->City;
    }
    
    /**
     * Set Country
     */
    public function setCountry(JJs\Bundle\GeonamesBundle\Entity\Country $country) {
    	$this->country = $country;
    }
    
    /**
     * Get Country
     *
     * @return string
     */
    public function getCountry() {
    	return $this->Country;
    }
    
    /**
     * Set Childrens
     */
    public function setChildrens(trazeo\Trazeo\BaseBundle\Entity\Children $childrens) {
    	$this->childrens = $childrens;
    }
    
    /**
     * Get Childrens
     *
     * @return string
     */
    public function getChildrens() {
    	return $this->Childrens;
    }
    
    
    /**
     * Get Groups
     *
     * @return string
     */
    public function getGroups() {
    	return $this->Groups;
    }
    
    
    /**
     * Set AdminGroups
     */
    public function setAdminGroup(Application\Sonata\UserBundle\Entity\Group $adminGroups) {
    	$this->adminGroups = $adminGroups;
    }
    
    /**
     * Get AdminGroups
     *
     * @return string
     */
    public function getAdminGroups() {
    	return $this->AdminGroups;
    }
    
    
    /**
     * Set Routes
     */
    public function setRoutes(trazeo\Trazeo\BaseBundle\Entity\Routes $routes) {
    	$this->routes = $routes;
    }
    
    /**
     * Get Routes
     *
     * @return string
     */
    public function getRoutes() {
    	return $this->Routes;
    }
    
    public function __toString() {
    	return $this->getNick();
    }
}